// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "43c204e9-3966-475a-8ce3-f1d1d7482322");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1541240714);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{242cfa07-aafa-4965-800c-5ac782b0b5db}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1541199600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1541240831);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1541244220824");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1541246002824");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1541240717584");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1541244317584");
user_pref("browser.search.region", "AT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181023214907");
user_pref("browser.slowStartup.averageTime", 642);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20181023214907");
user_pref("browser.startup.homepage_override.mstone", "63.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1541240717525");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181023214907");
user_pref("extensions.lastAppVersion", "63.0");
user_pref("extensions.lastPlatformVersion", "63.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"2f59c394-696e-4018-a6ed-0b61b004d025\",\"webcompat@mozilla.org\":\"2803ace9-647c-4c33-94d2-5b8ae8d1fefb\",\"screenshots@mozilla.org\":\"e6cb3394-88b6-4e5c-a591-39079c7afe6a\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "06e6ccf6-c2b2-419c-862a-097bd80d4d85");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1541244217);
user_pref("toolkit.telemetry.cachedClientID", "be5c1902-d1fd-4eb4-a7b8-9fbbba95e5c2");
user_pref("toolkit.telemetry.previousBuildID", "20181023214907");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
